general:
  # The time between saves
  save-interval: 5m
  # The time between updating scores. The only islands that will be recalculated are 
  # islands that have been modified by a player placing or removing a block on the island
  # since the last time the score was updated
  score-sweep-delay: 2m
  # The maximum time in milliseconds that can be spent each tick calculating the score of an island
  score-calc-time-limit: 10
  
  # The time between removing abandoned islands.
  abandon-sweep-delay: 2m

player:
  # When true, the players own island does not count towards the max-membership count 
  exclude-own: true
  # The maximum number of islands the player can be part of
  max-membership: 1

# Settings for islands
island:
  # The size in chunks. Default is 4x4 chunks giving a 64x64 area from y level 0 to 255
  size: 4
  # The template to use for building islands. These are located in the templates folder or inside the jar. Default is 'original'
  template: original
  # The minimum time between restarts 
  restart-cooldown: 1d
  # The maximum number of players that can be members of an island
  max-members: -1

# Below are the worlds that will be used as skyblock worlds
# You can have as many as you like.
worlds:
 - skyblock