# Settings for islands
island:
  # The size in chunks. Default is 4x4 chunks giving a 64x64 area from y level 0 to 255
  size: 4

# Below are the worlds that will be used as skyblock worlds
# You can have as many as you like.
worlds:
 - skyblock