general:
  # The time between saves
  save-interval: 5m
  # The time between updating scores. The only islands that will be recalculated are 
  # islands that have been modified by a player placing or removing a block on the island
  # since the last time the score was updated
  score-sweep-delay: 2m
  # The maximum time in milliseconds that can be spent each tick calculating the score of an island
  score-calc-time-limit: 10
  # The time between removing abandoned islands.
  abandon-sweep-delay: 2m
  # Islands must be older than this value to be removed with an /is admin cleanup
  cleanup-cutoff: 4mo
  # If true, the nether will be be used in skyblock. If not, the nether will not be accessible, though you can use another plugin to provide it
  use-nether: true
  # If true, each skyblock world will have a spawn island assigned
  spawn-islands: true

player:
  # When true, the players own island does not count towards the max-membership count 
  exclude-own: true
  # The maximum number of islands the player can be part of
  max-membership: 1
  reverse:
    # Allows you to reverse lava turning into obsidian
    lava: true
    # Allows you to reverse water turning into cobblestone or stone
    water: true

# Settings for islands
island:
  # The size in chunks. Default is 4x4 chunks giving a 64x64 area from y level 0 to 255
  size: 4
  # The y level the islands will be placed at.
  height: 190
  # The template to use for building islands. These are located in the templates folder or inside the jar. Default is 'original'
  template: original
  # The template to use for building the nether side islands. These are located in the templates folder or inside the jar. Default is 'original_nether'
  template-nether: original_nether
  # The template to use for building the spawn island
  template-spaawn: spawn
  # The minimum time between restarts 
  restart-cooldown: 1d
  # The maximum number of players that can be members of an island
  max-members: -1
  # The number of blocks around the edge of the island that becomes an unowned area.
  # In this area, anyone can build or destroy blocks
  # This amount will be deducted from the amount of space the island has
  neutral-zone-size: 4
  # Notify players when they leave the protected area of an island
  notify-on-leave: true
  # Notify players when they enter the protected area of an island
  notify-on-enter: true

# Below are the worlds that will be used as skyblock worlds
# You can have as many as you like.
worlds:
 - skyblock