name: SupremeSkyblock
author: Schmoller
version: ${project.version}

main: au.com.addstar.skyblock.SkyblockPlugin
load: STARTUP

softdepend: [WorldEdit]

commands:
  skyblock:
    usage: /<command>
    aliases: [island, sb, is]
    permission: skyblock.commands.skyblock

permissions:
# User commands
  skyblock.commands.skyblock:
    default: true
  skyblock.commands.restart:
    default: true
  skyblock.commands.info:
    default: true
  skyblock.command.challenge:
    default: true
  skyblock.command.rank:
    default: true
  skyblock.command.invite:
    default: true
  skyblock.command.kick:
    default: true
  skyblock.command.leave:
    default: true
  skyblock.command.home:
    default: true
# Admin commands
  skyblock.commands.template:
    default: op
  skyblock.commands.info.others:
    default: op
    children:
      skyblock.commands.info: true
  skyblock.commands.restart.others:
    default: op
    children:
      skyblock.commands.restart: true
# Other permissions
  skyblock.protection.bypass:
    default: op
  skyblock.cooldown.bypass:
    default: op