name: SupremeSkyblock
author: Schmoller
version: ${project.version}

main: au.com.addstar.skyblock.SkyblockPlugin
load: STARTUP

depend: [Monolith]
softdepend: [WorldEdit, Vault]

commands:
  skyblock:
    usage: /<command>
    aliases: [island, sb, is]
    permission: skyblock.commands.skyblock

permissions:
# User commands
  skyblock.commands.skyblock:
    default: false
  skyblock.commands.restart:
    default: false
  skyblock.commands.info:
    default: false
  skyblock.command.challenge:
    default: false
  skyblock.command.rank:
    default: false
  skyblock.command.invite:
    default: false
  skyblock.command.kick:
    default: false
  skyblock.command.leave:
    default: false
  skyblock.command.home:
    default: false
  skyblock.command.transfer:
    default: false
  skyblock.command.sethome:
    default: false
  skyblock.command.warp:
    default: false
  skyblock.command.togglewarp:
    default: false
# Admin commands
  skyblock.command.admin:
    default: false
  skyblock.commands.template:
    default: false
  skyblock.commands.info.others:
    default: false
    children:
      skyblock.commands.info: true
  skyblock.commands.restart.others:
    default: false
    children:
      skyblock.commands.restart: true
  skyblock.commands.goto:
    default: false
  skyblock.command.reload:
    default: false
# Bypass permissions
  skyblock.bypass.protection:
    default: false
  skyblock.bypass.cooldown:
    default: false
# Group permissions
  skyblock.group.player:
    default: true
    children:
      skyblock.commands.skyblock: true
      skyblock.commands.restart: true
      skyblock.commands.info: true
      skyblock.command.challenge: true
      skyblock.command.rank: true
      skyblock.command.invite: true
      skyblock.command.kick: true
      skyblock.command.leave: true
      skyblock.command.home: true
      skyblock.command.transfer: true
      skyblock.command.sethome: true
      skyblock.command.warp: true
      skyblock.command.togglewarp: true
  skyblock.group.moderator:
    default: op
    children:
      skyblock.group.player: true
      skyblock.command.admin: true
      skyblock.commands.info.others: true
      skyblock.commands.restart.others: true
      skyblock.commands.goto: true
      skyblock.bypass.cooldown: true
      skyblock.bypass.protection: true
  skyblock.group.admin:
    default: op
    children:
      skyblock.group.moderator: true
      skyblock.commands.template: true
      skyblock.command.reload: true