name: SupremeSkyblock
author: Schmoller
version: ${project.version}

main: au.com.addstar.skyblock.SkyblockPlugin
load: STARTUP

depend: [Monolith]
softdepend: [WorldEdit, Vault]

commands:
  skyblock:
    usage: /<command>
    aliases: [island, sb, is]
    permission: skyblock.commands.skyblock

permissions:
# User commands
  skyblock.commands.skyblock:
    default: true
  skyblock.commands.restart:
    default: true
  skyblock.commands.info:
    default: true
  skyblock.command.challenge:
    default: true
  skyblock.command.rank:
    default: true
  skyblock.command.invite:
    default: true
  skyblock.command.kick:
    default: true
  skyblock.command.leave:
    default: true
  skyblock.command.home:
    default: true
  skyblock.command.transfer:
    default: true
# Admin commands
  skyblock.command.admin:
    default: op
  skyblock.commands.template:
    default: op
  skyblock.commands.info.others:
    default: op
    children:
      skyblock.commands.info: true
  skyblock.commands.restart.others:
    default: op
    children:
      skyblock.commands.restart: true
  skyblock.commands.goto:
    default: op
  skyblock.command.reload:
    default: op
# Other permissions
  skyblock.protection.bypass:
    default: op
  skyblock.cooldown.bypass:
    default: op