package au.com.addstar.skyblock;

import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;

import org.bukkit.Bukkit;
import org.bukkit.World;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.configuration.InvalidConfigurationException;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.configuration.file.YamlConfiguration;

public class SkyblockManager
{
	private HashMap<World, SkyblockWorld> mWorlds;
	private SkyblockPlugin mPlugin;
	
	public SkyblockManager(SkyblockPlugin plugin)
	{
		mPlugin = plugin;
		mWorlds = new HashMap<World, SkyblockWorld>();
	}
	
	public void loadWorlds(ConfigurationSection config)
	{
		File worldDir = new File(mPlugin.getDataFolder(), "worlds");
		
		if (!worldDir.exists())
			worldDir.mkdirs();
		
		mWorlds.clear();
		
		List<String> worldNames = config.getStringList("worlds");
		for(String name : worldNames)
		{
			name = name.toLowerCase();
			if (mWorlds.containsKey(name))
			{
				mPlugin.getLogger().warning("The world '" + name + "' is already defined as a skyblock world");
				continue;
			}
			
			// Dont process existing worlds
			if (Bukkit.getWorld(name) != null)
				continue;
			
			File worldFile = new File(worldDir, name);
			FileConfiguration worldConfig = new YamlConfiguration();
			
			try
			{
				if (worldFile.exists())
				{
					try
					{
						worldConfig.load(worldFile);
					}
					catch(InvalidConfigurationException e)
					{
						mPlugin.getLogger().warning("World setting file for " + name + " failed to load. A default file will be used instead.");
						e.printStackTrace();
					}
				}
				
				SkyblockWorld world = new SkyblockWorld(name, worldConfig);
				mWorlds.put(world.getWorld(), world);
				
				world.save(worldConfig);
				worldConfig.options().header("WARNING! Do not edit this file, it is automatically generated. Any changes made can adversely affect the world linked to this file");
				worldConfig.save(worldFile);
			}
			catch(IOException e)
			{
				mPlugin.getLogger().severe("Error loading skyblock world '" + name + "':");
				e.printStackTrace();
			}
		}
	}
}
